# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    twig.class_extension:
        class: AppBundle\Twig\ClassnameTwigExtension
        tags:
            - { name: twig.extension }
